name: Retrain Model with Feedback

on:
  schedule:
    # Every night at 2 UTC
    - cron: "0 2 * * *"
  workflow_dispatch: # allows manual run

permissions:
  contents: write
  
jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install mediapipe opencv-python-headless scikit-learn joblib supabase

      - name: Retrain with feedback
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        run: |
          python retrain_with_feedback.py

      - name: Commit and push new model
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add model/handcricket_feedback.pkl
          git commit -m "Retrained model with latest feedback"
          git push